# -*- coding: utf-8 -*-
"""demandabse

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLwF7bdyTN_9nduDuqink8P6brvLFPX9
"""

import pandas as pd

df = pd.read_csv("Indias_Electricity_Consumption_Dataset.csv")

print(df.shape)
print(df.columns.tolist())

df.head()

import pandas as pd

df = pd.read_csv("Indias_Electricity_Consumption_Dataset.csv")

print(df.info())
print()

print(df.describe())
print()

print(df.isnull().sum())
print()

print("Duplicate Rows :", df.duplicated().sum())

df["Dates"] = pd.to_datetime(df["Dates"])

print(df["Dates"].min())
print(df["Dates"].max())

"""renaming the state names

"""

df.rename(columns={
    "Unnamed: 0": "Index",
    "DD": "Daman and Diu",
    "DNH": "Dadra and Nagar Haveli",
    "HP": "Himachal Pradesh",
    "J&K": "Jammu and Kashmir",
    "MP": "Madhya Pradesh",
    "UP": "Uttar Pradesh",
    "Pondy": "Puducherry",
    "DVC": "Damodar Valley Corporation"
}, inplace=True)

print(df.columns.tolist())

"""Handling missing values"""

missing_cols = df.columns[df.isnull().any()]

for col in missing_cols:
    print("="*60)
    print(col)
    print(df[df[col].isnull()][["Dates", col]].head(10))

# Remove columns that are not needed
df.drop(columns=["Index", "Essar steel"], inplace=True)

# Sort by date (good practice)
df = df.sort_values("Dates").reset_index(drop=True)

print(df.shape)
print(df.columns.tolist())

df_long = df.melt(
    id_vars=["Dates", "Total Consumption"],
    var_name="State",
    value_name="Consumption"
)

print(df_long.shape)

# Sort by State and Date
df_long = df_long.sort_values(["State", "Dates"]).reset_index(drop=True)

# Fill Total Consumption
df_long["Total Consumption"] = df_long["Total Consumption"].interpolate()

# Interpolate each state's consumption
df_long["Consumption"] = (
    df_long.groupby("State")["Consumption"]
           .transform(lambda s: s.interpolate(method="linear",
                                              limit_direction="both"))
)

print(df_long.isnull().sum())

"""**Feature Engineering**"""

# Date features
df_long["Year"] = df_long["Dates"].dt.year
df_long["Month"] = df_long["Dates"].dt.month
df_long["Month_Name"] = df_long["Dates"].dt.month_name()
df_long["Quarter"] = df_long["Dates"].dt.quarter
df_long["Day"] = df_long["Dates"].dt.day
df_long["Day_Name"] = df_long["Dates"].dt.day_name()
df_long["Week"] = df_long["Dates"].dt.isocalendar().week.astype(int)

# Weekend indicator
df_long["Is_Weekend"] = df_long["Day_Name"].isin(["Saturday", "Sunday"])

def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Summer"
    elif month in [6, 7, 8, 9]:
        return "Monsoon"
    else:
        return "Post-Monsoon"

df_long["Season"] = df_long["Month"].apply(get_season)

df_long.head()

print("="*50)
print("DATASET SUMMARY")
print("="*50)

print("Rows :", df_long.shape[0])
print("Columns :", df_long.shape[1])

print("\nDate Range")
print(df_long["Dates"].min())
print(df_long["Dates"].max())

print("\nNumber of States")
print(df_long["State"].nunique())

print("\nMissing Values")
print(df_long.isnull().sum())

"""National Electricity Consumption Trend"""

import matplotlib.pyplot as plt

daily_total = (
    df_long.groupby("Dates")["Total Consumption"]
           .first()
)

plt.figure(figsize=(15,6))

plt.plot(daily_total.index,
         daily_total.values,
         linewidth=1)

plt.title("India's Daily Electricity Consumption (2013–2024)", fontsize=16)

plt.xlabel("Year")
plt.ylabel("Consumption (MU)")

plt.grid(alpha=0.3)

plt.tight_layout()

plt.show()

"""Top 10 Electricity Consuming States"""

state_total = (
    df_long.groupby("State")["Consumption"]
           .sum()
           .sort_values(ascending=False)
           .head(10)
)

plt.figure(figsize=(10,6))

plt.barh(state_total.index,
         state_total.values)

plt.title("Top 10 Electricity Consuming States")

plt.xlabel("Total Consumption (MU)")

plt.gca().invert_yaxis()

plt.tight_layout()

plt.show()

"""Distribution of Consumption"""

plt.figure(figsize=(10,5))

plt.hist(df_long["Consumption"].dropna(),
         bins=40)

plt.title("Distribution of Electricity Consumption")

plt.xlabel("Consumption (MU)")

plt.ylabel("Frequency")

plt.tight_layout()

plt.show()

"""Monthly Trend"""

monthly = (
    df_long.groupby("Month_Name")["Consumption"]
           .mean()
)

order = ["January","February","March","April","May","June",
         "July","August","September","October","November","December"]

monthly = monthly.reindex(order)

plt.figure(figsize=(12,5))

plt.plot(monthly.index,
         monthly.values,
         marker="o")

plt.xticks(rotation=45)

plt.title("Average Monthly Electricity Consumption")

plt.ylabel("Consumption (MU)")

plt.grid(alpha=0.3)

plt.tight_layout()

plt.show()

"""Year-wise Electricity Consumption Trend

"""

yearly = (
    df_long.groupby("Year")["Total Consumption"]
           .mean()
)

plt.figure(figsize=(10,5))

plt.plot(yearly.index,
         yearly.values,
         marker='o',
         linewidth=2)

plt.title("Average Year-wise Electricity Consumption", fontsize=15)
plt.xlabel("Year")
plt.ylabel("Average Consumption (MU)")
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

"""Seasonal Consumption"""

seasonal = (
    df_long.groupby("Season")["Consumption"]
           .mean()
           .reindex(["Winter","Summer","Monsoon","Post-Monsoon"])
)

plt.figure(figsize=(8,5))

plt.bar(seasonal.index,
        seasonal.values)

plt.title("Average Electricity Consumption by Season")
plt.xlabel("Season")
plt.ylabel("Average Consumption (MU)")

plt.tight_layout()
plt.show()

"""Weekday vs Weekend"""

weekday = (
    df_long.groupby("Is_Weekend")["Consumption"]
           .mean()
)

weekday.index = ["Weekday","Weekend"]

plt.figure(figsize=(6,5))

plt.bar(weekday.index,
        weekday.values)

plt.title("Weekday vs Weekend Electricity Consumption")
plt.ylabel("Average Consumption (MU)")

plt.tight_layout()
plt.show()

"""State-wise Boxplot"""

top10 = (
    df_long.groupby("State")["Consumption"]
           .mean()
           .sort_values(ascending=False)
           .head(10)
           .index
)

plot_df = df_long[df_long["State"].isin(top10)]

plt.figure(figsize=(14,6))

plot_df.boxplot(
    column="Consumption",
    by="State",
    rot=45
)

plt.title("Consumption Distribution of Top 10 States")
plt.suptitle("")
plt.xlabel("")
plt.ylabel("Consumption (MU)")

plt.tight_layout()
plt.show()

"""Correlation Heatmap"""

pivot = (
    df_long.groupby(["Year","Month"])["Consumption"]
           .mean()
           .unstack()
)

plt.figure(figsize=(10,6))

plt.imshow(pivot,
           aspect="auto")

plt.colorbar(label="Average Consumption")

plt.xticks(range(12),
["Jan","Feb","Mar","Apr","May","Jun",
 "Jul","Aug","Sep","Oct","Nov","Dec"])

plt.yticks(range(len(pivot.index)),
           pivot.index)

plt.title("Monthly Electricity Consumption Heatmap")

plt.tight_layout()
plt.show()

"""Top 5 State Trend Comparison"""

top5 = (
    df_long.groupby("State")["Consumption"]
           .sum()
           .sort_values(ascending=False)
           .head(5)
           .index
)

plt.figure(figsize=(15,6))

for state in top5:
    temp = df_long[df_long["State"]==state]
    plt.plot(temp["Dates"],
             temp["Consumption"],
             label=state)

plt.legend()

plt.title("Top 5 States Electricity Consumption Trend")

plt.xlabel("Year")
plt.ylabel("Consumption (MU)")

plt.tight_layout()

plt.show()

"""Top 5 State Trend Comparison

"""

india = (
    df_long.groupby("Dates")["Total Consumption"]
           .first()
)

rolling = india.rolling(30).mean()

plt.figure(figsize=(15,6))

plt.plot(india,
         alpha=0.4,
         label="Daily")

plt.plot(rolling,
         linewidth=2,
         label="30-Day Rolling Average")

plt.legend()

plt.title("Daily vs Rolling Average Electricity Consumption")

plt.tight_layout()

plt.show()

df_long.to_csv("power_consumption_clean.csv", index=False)